~VERSION INFORMATION
VERS. 2.0 : CWLS LOG ASCII STANDARD - VERSION 2.0
WRAP. NO : ONE LINE PER DEPTH STEP

~WELL INFORMATION
#MNEM.UNIT      DATA                 DESCRIPTION
STRT.M          100.0                START DEPTH
STOP.M          140.0                STOP DEPTH
NULL.           -999.25              NULL VALUE
WELL.           WELL-1               WELL NAME

~CURVE INFORMATION
#MNEM.UNIT      DESCRIPTION
DEPT.M          DEPTH
GR.API          GAMMA RAY

~A
100.0  45.5
110.0  46.0
120.0  46.7
130.0  96.7
140.0  47.3